### ISSUE TITLE
ValueError: could not convert string to float: 'start'

### ISSUE THREAD

**Issue by weizhousjtu** [brentp/combined-pvalues#26]
Traceback (most recent call last):
  File "/home/anaconda3/bin/comb-p", line 4, in <module>
    __import__('pkg_resources').run_script('cpv==0.50.2', 'comb-p')
  File "/home/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/EGG-INFO/scripts/comb-p", line 39, in <module>
    main()
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/EGG-INFO/scripts/comb-p", line 36, in main
    module.main()
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/pipeline.py", line 77, in main
    use_fdr=not args.no_fdr)
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/pipeline.py", line 89, in pipeline
    step = min(acf_dist, stepsize.stepsize(bed_files, col_num))
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/stepsize.py", line 19, in stepsize
    L = list(chromlist)
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/_common.py", line 64, in bediter
    start = int(float(l[1]))
ValueError: could not convert string to float: 'start'

I installed the latest version but still wrong, does anyone could help me?

**Comment by brentp** [comment]
hi, you can add a '#' to the start of your header line so that comb-p knows it's a header.

**Comment by weizhousjtu** [comment]
thank you！ I add a '#' to the start of header line, it worked. however, another error occured.
`comb-p pipeline -c 4 --seed 0.01 --dist 500 --region-filter-p 0.01 \
> -p ./ --annotate hg19 cgInfor_combp_final_sort.bed
setting --acf-dist to 0.33 * --dist == 170
calculated stepsize as: 170
ACF:
 #lag_min       lag_max correlation     N       p
1       171     0.1543  115308  0
wrote: ./.acf.txt

# original lambda: 1.38
wrote: ./.slk.bed.gz with lambda: 1.42
wrote: ./.fdr.bed.gz
wrote: ./.regions.bed.gz (14 regions)
# read 14 regions from ./.regions.bed.gz
# calculating ACF out to: 166
#           with 2  lags: [1, 171]
# Done with one-time ACF calculation
361348 bases used as coverage for sidak correction
"warning: 0-length region found.
does input have 0-length intervals? using length of 1 and not reporting
further 0-length intervalswrote: ./.regions-p.bed.gz, (regions with corrected-p < 0.05: 7)
Traceback (most recent call last):
  File "/home/anaconda3/bin/comb-p", line 4, in <module>
    __import__('pkg_resources').run_script('cpv==0.50.2', 'comb-p')
  File "/home/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/EGG-INFO/scripts/comb-p", line 39, in <module>
    main()
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/EGG-INFO/scripts/comb-p", line 36, in main
    module.main()
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/pipeline.py", line 77, in main
    use_fdr=not args.no_fdr)
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/pipeline.py", line 183, in pipeline
    regions_bed, p_col_name=col_num)):
  File "/home/anaconda3/lib/python3.7/site-packages/cpv-0.50.2-py3.7.egg/cpv/filter.py", line 73, in filter
    raise Exception('need header in p-value file to run filter')
Exception: need header in p-value file to run filter`

**Comment by brentp** [comment]
can you show the output of `head -1 cgInfor_combp_final_sort.bed`

**Comment by weizhousjtu** [comment]
head -1 cgInfor_combp_final_sort.bed
`chr1	10850	10850	0.805014817073095	0.247123295906677`
it seems the header line is missing after run the script upon

**Comment by brentp** [comment]
no. comb-p doesn't alter the original file, you gave it a file without a header and/or  you sorted the header to somewhere other than the first line of the file.

**Comment by weizhousjtu** [comment]
yes, I must sorted first and add the header line. thank you for your explain!
