### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by D-Regano** [brentp/combined-pvalues#34]
Hi.
I have recently installed and are trying to run comb-p. However, I am encountering errors when trying to run:
$ comb-p pipeline -c 4 --seed 0.05 --dist 500 -p new --region-filter-p 0.1 --anno hg19 filer/TSbed2.bed
setting --acf-dist to 0.33 * --dist == 170
Traceback (most recent call last):
  File "/home/is/anaconda3/bin/comb-p", line 39, in <module>
    main()
  File "/home/is/anaconda3/bin/comb-p", line 36, in main
    module.main()
  File "/home/is/anaconda3/lib/python3.7/site-packages/cpv/pipeline.py", line 79, in main
    use_fdr=not args.no_fdr)
  File "/home/is/anaconda3/lib/python3.7/site-packages/cpv/pipeline.py", line 91, in pipeline
    step = min(acf_dist, stepsize.stepsize(bed_files, col_num))
  File "/home/is/anaconda3/lib/python3.7/site-packages/cpv/stepsize.py", line 18, in stepsize
    for _, chromlist in groupby(bediter(bed_file, col), itemgetter('chrom')):
  File "/home/is/anaconda3/lib/python3.7/site-packages/cpv/_common.py", line 60, in bediter
    float(l[col_num])
IndexError: list index out of range

Does anyone have any idea of what is wrong here?

**Comment by D-Regano** [comment]
Found out my .bed file was space separated and not tab separated, It´s now working.
