### ISSUE TITLE
NameError after Fix #32 was pushed on September 3rd 2021

### ISSUE THREAD

**Issue by annekristin** [brentp/combined-pvalues#35]
Trackback:
Traceback (most recent call last):
  File "/home/annes/anaconda3/bin/comb-p", line 39, in <module>
    main()
  File "/home/annes/anaconda3/bin/comb-p", line 36, in main
    module.main()
  File "/home/annes/.local/lib/python3.8/site-packages/cpv/pipeline.py", line 71, in main
    return pipeline(col_num, args.step,
  File "/home/annes/.local/lib/python3.8/site-packages/cpv/pipeline.py", line 206, in pipeline
    manhattan.manhattan(prefix + ".slk.bed.gz", 3, prefix.rstrip(".") + ".manhattan.png",
  File "/home/annes/.local/lib/python3.8/site-packages/cpv/manhattan.py", line 89, in manhattan
    for seqid, rlist in sorted(giter, key=cmp_to_key(chr_cmp)):
  File "/home/annes/.local/lib/python3.8/site-packages/cpv/manhattan.py", line 57, in chr_cmp
    return cmp(int(achr), int(bchr))
NameError: name 'cmp' is not defined

**Comment by brentp** [comment]
will you try latest commit just pushed?
(you can git clone then run `python setup.py install` from the combined-pvalues directory)

**Comment by annekristin** [comment]
Perfect! Thank you. 
No error messages, and chromosomes are sorted as expected in the manhattan plot.

Thank you for sorting this out so quickly!

**Comment by brentp** [comment]
great! thanks for following up.
